import 'dart:io';

import 'package:path/path.dart' as p;

import '../logging/app_logger.dart';

/// Persists user environment variables on Linux/macOS by writing them to a
/// sourced script and wiring it into the user's shell rc files, so shells
/// opened after this runs — including ones this app never spawned — see
/// them without manual setup. The counterpart to `WindowsEnvVars`, which
/// does the same job via the registry; a no-op on Windows.
class UnixEnvVars {
  UnixEnvVars._();

  static const _beginMarker = '# >>> waydir env >>>';
  static const _endMarker = '# <<< waydir env <<<';

  static const _rcFileNames = [
    '.bashrc',
    '.zshrc',
    '.bash_profile',
    '.zprofile',
    '.profile',
  ];

  /// Writes [vars] to `<supportDir>/env.sh` and ensures each existing shell
  /// rc file under the home directory sources it.
  static void persist(String supportDir, Map<String, String> vars) {
    if (!Platform.isLinux && !Platform.isMacOS) return;
    try {
      final scriptPath = p.join(supportDir, 'env.sh');
      final script = _renderScript(vars);
      final file = File(scriptPath);
      if (!file.existsSync() || file.readAsStringSync() != script) {
        file.writeAsStringSync(script);
      }
      final home = Platform.environment['HOME'];
      if (home == null || home.isEmpty) return;
      for (final name in _rcFileNames) {
        _ensureSourced(p.join(home, name), scriptPath);
      }
    } catch (e, st) {
      log.warn('terminal', 'failed to persist env vars', error: e, stack: st);
    }
  }

  static String _renderScript(Map<String, String> vars) {
    final buffer = StringBuffer()
      ..writeln('# Generated by Waydir — do not edit by hand.');
    for (final entry in vars.entries) {
      buffer.writeln('export ${entry.key}="${entry.value}"');
    }

    return buffer.toString();
  }

  static void _ensureSourced(String rcPath, String scriptPath) {
    final rc = File(rcPath);
    if (!rc.existsSync()) return;
    final content = rc.readAsStringSync();
    if (content.contains(_beginMarker)) return;
    final block =
        '\n$_beginMarker\n[ -f "$scriptPath" ] && . "$scriptPath"\n$_endMarker\n';
    rc.writeAsStringSync(content + block);
  }
}
